# Generated by Django 2.2.3 on 2020-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('precautions', models.TextField()),
                ('safty', models.TextField()),
            ],
        ),
    ]
